### ISSUE TITLE
Aquire PhotoSizes from device and don't hardcode them

### ISSUE THREAD

**Issue by SrTobi** [Apparence-io/camera_awesome#142]
## Proposal

From what I saw in the iOS implementation, the photo sizes are hardcoded to the standard presets.
Is there a particular reason why they are not queried from the device? Looks to me as if [AVCaptureDevice.formats](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1388738-formats) is what holds this information.
Would be very useful.

**Comment by istornz** [comment]
Hi @SrTobi, formats are now [directly fetched from the device](https://github.com/Apparence-io/camera_awesome/blob/9501da00f5fad2fd89a1997f531c1fc5051c4d13/ios/Classes/Utils/CameraQualities.m#L84).

Some value are [hardcoded](https://github.com/Apparence-io/camera_awesome/blob/9501da00f5fad2fd89a1997f531c1fc5051c4d13/ios/Classes/Utils/CameraQualities.m#L63) for the moment because we planed to change the system asap (we planned to use a generic enum for the quality instead of setting static resolution).
