### ISSUE TITLE
why not depend on the flutter-maintained camera plugin?

### ISSUE THREAD

**Issue by NANASHI0X74** [Apparence-io/camera_awesome#74]
Hi, I've been looking for any ready-made widgets to take pictures in flutter and so far this looks the most promising, I just have a quick question: there's a camera plugin that the flutter team seems to be maintaining for a couple years now: https://pub.dev/packages/camera
Taking a quick look at this, it seems like you're not using that and instead I suppose you're writing the interfacing code yourself, right? I'm just curious as to what the reason was to decide so.

**Comment by g-apparence** [comment]
Hi, 
the reason is because the official plugin was not maintained months ago when we started this. 
So we decided to make a try to help the community. Maybe this pushed the flutter team to work again on the official camera plugin... Anyway we have fun working on this plugin so when we can we fix and add new features.
